name: 'dart_summit_2016'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  box2d: '^0.2.0'
  backy: '^0.2.1'
  darwin: '^0.2.4'


transformers:
- dart_to_js_script_rewriter
